### ISSUE TITLE
Modify the README.md file

### ISSUE THREAD

**Issue by KenniBlank** [KenniBlank/ShooterGame2D#2]
> DO NOT USE GENERATIVE AI for all the work
Create a proper readme file.
- Most of the sprite are from craftpix.net, include this
- font for game is from google font
- Link the SDL_2 documentation page
- Set A section aside for contributors and add your github link in format [Name](Link)
- Create a Documentation Section and development update section.
Feel free to add in anything else.   
Also add proper project name or just PLACEHOLDER.
- Also add the prerequirements: You can view what's needed from the Makefile

**Comment by anjali-vaish** [comment]
@KenniBlank I'd want to contribute, could you please assign this to me. Thanks!

**Comment by Satyasn01** [comment]
@KenniBlank I'd want to contribute, could you please assign this to me. Thanks!

**Comment by KenniBlank** [comment]
Absolutely. Here you Go

**Comment by KenniBlank** [comment]
Marvelous Job.
