### ISSUE TITLE
Game keeps trying to open font file even if it isn't available the first time

### ISSUE THREAD

**Issue by 9x14S** [KenniBlank/ShooterGame2D#4]
Bug: 
![image](https://github.com/user-attachments/assets/1c2ea345-53b4-4350-8b7f-dd142c7ac919)

It happens at this line: 
![image](https://github.com/user-attachments/assets/27a33828-e868-4de1-a1d6-c8df36b0ae52)
in mainGame.c

**Comment by KenniBlank** [comment]
I think I have located the issue, I will fix it right away. 
Thank you.

**Comment by KenniBlank** [comment]
Can you check if the issue still exists.

**Comment by KenniBlank** [comment]
> The solution would be to set up the fonts before the game loop, so that they're loaded only once

Initially that was the intended solution but I have two font files that need to be edited with their font sizes. I couldn't find a proper solution for that issue so the current solution exits.
I will try to clean that issue up by initializing beforehand. Thanks

**Comment by BISHALTWR** [comment]
### Got this error:

![image](https://github.com/user-attachments/assets/8a753538-47d3-42c2-a812-0eca71ec0fea)

**Comment by BISHALTWR** [comment]
- Got the same issue mentioned by @9x14S after i died in game
![image](https://github.com/user-attachments/assets/9a339d57-704a-4532-a02f-6ca664d1a085)

**Comment by BISHALTWR** [comment]
- The issue was solved in latest commit
![image](https://github.com/user-attachments/assets/a793b5a1-35bd-4c1c-9700-c617621ecb7a)

**Comment by KenniBlank** [comment]
@9x14S 
Is the error present?
